// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OctalToBinary(arg1) {
  return window['go']['main']['App']['OctalToBinary'](arg1);
}
